### PR TITLE
🚀 Add axios as a dependency to nyts

### PR DESCRIPTION
**Pull request by yeskunall**
This PR will introduce many additions to the `nyts` package, now that I've decided on using [`axios`](https://github.com/mzabriskie/axios) within `nyts` to make requests.

All work (experimental and otherwise) related to integrating `axios` is expected to go here, as the plan is to merge this into the parent stream at some point in the future, indicating that `nyts` works as expected. Hence, this PR won't be merged for a while.

### CODE REVIEW

**Comment by yeskunall** [comment]
Quickly realizing that `defaultConfig.js` might be redundant as we already have `endpoints.js`. I think we can arrive at a better standpoint if we somehow can integrate the two together. I'm thinking something like

```js
// defaultConfig.js
module.exports = {
  baseURL: 'https://yts.ag/api/v2',
};
```

```js
// request.js
// use defaultConfig here instead
```

... and refactor `endpoints.js` to only contain the necessary parts of the URL, i.e., everything after the `baseURL`.

Are you willing to make the changes @arungalva? Let me know your thoughts as well.

**Comment by arungalva** [comment]
I don't think we need defaultconfig.js yet since we don't have anything except the base url there which can go into the endpoints.js file. 

However, if we need to store any other default values that are not urls, we might need to bring it back

**Comment by yeskunall** [comment]
I'll see what I can do. Ping you once I make the changes, I guess. @arungalva

**Comment by yeskunall** [comment]
In the meantime, adding tests. :white_check_mark:

**Comment by yeskunall** [comment]
Don't know how the editor missed it, but [this](https://github.com/yeskunall/nyts/blob/83f14d89ffc35276d61fb121b70c80c2e3fb3c33/lib/nyts.js#L81) needs to be fixed. Also, Jest mocks for testing if the HTTP request util works or not. Then some clean up and this branch is ready to be merged. 👍

**Comment by yeskunall** [comment]
Look into [`ava`](https://github.com/avajs/ava) + [`nock`](https://github.com/node-nock/nock) for the tests.

**Pull request merged**
